// Certora specification for LudusEvents - Treasury Invariant

/// Checks if the treasury distribution property holds for a specific eventId.
/// Returns true if the event doesn't exist (property holds vacuously) or if the property holds.
function checkTreasuryDistributionProperty(uint256 eventId) returns bool {
    uint256 id_ev; uint256 startTime_ev; uint256 endTime_ev; uint256 regStartTime_ev; uint256 regEndTime_ev;
    uint256 maxParticipants_ev; uint256 minParticipantsToStart_ev; address creator_ev; address referee_ev;
    uint status_ev; uint256 regFee_ev; uint paymentCurrency_ev; uint256 totalPrize_ev; 
    bool prefYield_ev; bool yieldActivated_ev;

    // Updated tuple to match the new EventDetails struct
    (id_ev, startTime_ev, endTime_ev, regStartTime_ev, regEndTime_ev,
     maxParticipants_ev, minParticipantsToStart_ev, creator_ev, referee_ev, status_ev,
     regFee_ev, paymentCurrency_ev, totalPrize_ev, prefYield_ev, yieldActivated_ev) = events(eventId);

    // If id_ev is 0, it implies the event doesn't exist or is not initialized properly.
    if (id_ev == 0) { 
        return true;
    }
    // If an eventId is passed that doesn't match the fetched id_ev (and id_ev is not 0), 
    // it's an inconsistent state or looking up a non-existent event with a non-zero eventId.
    // The invariant will be checked for relevant eventIds generated by the tool.
    if (id_ev != eventId && id_ev != 0) { // Corrected logic from previous version
        return true; // Property holds vacuously for an eventId that doesn't map to itself.
    }

    uint256 athletesShare_dist; uint256 organizerShare_dist; uint256 charityShare_dist; address charityAddress_dist;
    (athletesShare_dist, organizerShare_dist, charityShare_dist, charityAddress_dist) = eventDistributions(eventId);
    
    bool distributionSumCorrect = (athletesShare_dist + organizerShare_dist + charityShare_dist == 9700);
    // Ensure charity address is non-zero if charity share is greater than zero.
    bool charityAddressValid = ((charityShare_dist == 0) || (charityAddress_dist != 0x0000000000000000000000000000000000000000));
    
    return distributionSumCorrect && charityAddressValid;
}

methods {
    function events(uint256 eventId) external returns (uint256, uint256, uint256, uint256, uint256, uint256, uint256, address, address, uint, uint256, uint, uint256, bool, bool) envfree;
    function eventDistributions(uint256 eventId) external returns (uint256, uint256, uint256, address) envfree;
    function eas() external returns (address) envfree;
    function schemaRegistry() external returns (address) envfree;
    function createEvent(bytes) external returns (uint256) optional envfree;
    function registerParticipant(uint256 eventId, address participant) external optional envfree;
    function completeEventAndDistribute(uint256 eventId, address[] winners, uint256[] prizeAmountsETH, uint256[] prizeAmountsUSDC) external optional envfree;
    function cancelEvent(uint256 eventId) external optional envfree;
    function activateYieldGeneration(uint256 eventId) external optional envfree;
    function getEventDetails(uint256 eventId) external returns (bytes) optional envfree;
    function getParticipantCount(uint256 eventId) external returns (uint256) optional envfree;
    function getTotalPrizePoolETH(uint256 eventId) external returns (uint256) optional envfree;
    function getTotalPrizePoolUSDC(uint256 eventId) external returns (uint256) optional envfree;
    function getEventStatus(uint256 eventId) external returns (uint8) optional envfree;
    function getEventOrganizer(uint256 eventId) external returns (address) optional envfree;
    // EAS function summaries - simplified to avoid complex tuple syntax issues
    function attest(bytes) external returns (bytes32) optional envfree;
    function setSchemaIds(bytes32, bytes32) external optional envfree;
}

/**
 * Invariant: Checks valid treasury distribution for all (relevant) eventIds.
 * This invariant ensures that for any event, the sum of percentage shares for athletes, 
 * organizer, and charity equals 9700 (97%), and if a charity share is defined, 
 * a valid charity address is also provided. This is based on the data stored in `eventDistributions`.
 */
invariant validTreasuryDistribution(uint256 eventId)
    checkTreasuryDistributionProperty(eventId); 