// Certora specification for LudusEvents - Treasury Invariant

/// Checks if the treasury distribution property holds for a specific eventId.
/// Returns true if the event doesn't exist (property holds vacuously) or if the property holds.
function checkTreasuryDistributionProperty(uint256 eventId) returns bool {
    uint256 id_ev; uint256 startTime_ev; uint256 endTime_ev; uint256 regStartTime_ev; uint256 regEndTime_ev;
    uint256 maxParticipants_ev; uint256 minParticipantsToStart_ev; address creator_ev; address referee_ev;
    uint status_ev; uint256 regFee_ev; uint paymentCurrency_ev; uint256 totalPrize_ev; 
    bool prefYield_ev; bool yieldActivated_ev;

    // Updated tuple to match the new EventDetails struct
    (id_ev, startTime_ev, endTime_ev, regStartTime_ev, regEndTime_ev,
     maxParticipants_ev, minParticipantsToStart_ev, creator_ev, referee_ev, status_ev,
     regFee_ev, paymentCurrency_ev, totalPrize_ev, prefYield_ev, yieldActivated_ev) = events(eventId);

    // If id_ev is 0, it implies the event doesn't exist or is not initialized properly.
    if (id_ev == 0) { 
        return true;
    }
    // If an eventId is passed that doesn't match the fetched id_ev (and id_ev is not 0), 
    // it's an inconsistent state or looking up a non-existent event with a non-zero eventId.
    // The invariant will be checked for relevant eventIds generated by the tool.
    if (id_ev != eventId && id_ev != 0) { // Corrected logic from previous version
        return true; // Property holds vacuously for an eventId that doesn't map to itself.
    }

    uint256 athletesShare_dist; uint256 organizerShare_dist; uint256 charityShare_dist; address charityAddress_dist;
    (athletesShare_dist, organizerShare_dist, charityShare_dist, charityAddress_dist) = eventDistributions(eventId);
    
    bool distributionSumCorrect = (athletesShare_dist + organizerShare_dist + charityShare_dist == 9700);
    // Ensure charity address is non-zero if charity share is greater than zero.
    bool charityAddressValid = ((charityShare_dist == 0) || (charityAddress_dist != 0x0000000000000000000000000000000000000000));
    
    return distributionSumCorrect && charityAddressValid;
}

methods {
    // State readers
    // Updated signature for events mapping accessor to reflect EventDetails struct changes
    function events(uint256 eventId) external returns (
        uint256, // id
        uint256, // startTime
        uint256, // endTime
        uint256, // registrationStartTime
        uint256, // registrationEndTime
        uint256, // maxParticipants
        uint256, // minParticipantsToStart
        address, // creator
        address, // referee
        uint,    // status (LudusTypes.EventStatus as uint)
        uint256, // registrationFee
        uint,    // paymentCurrency (LudusTypes.PaymentToken as uint)
        uint256, // totalPrizePool
        bool,    // preferYieldGeneration
        bool     // yieldActivated
    ) envfree;
    function eventDistributions(uint256 eventId) external returns (uint256, uint256, uint256, address) envfree;

    // External Contract Accessors (as seen by LudusEvents)
    function yieldManager() external returns (address) envfree; 
    function USDC() external returns (address) envfree; 
    function ludusIdentity() external returns (address) envfree;
    function eas() external returns (address) envfree;
    function schemaRegistry() external returns (address) envfree;


    // State changers in LudusEvents
    function createEvent(LudusTypes.EventCreationParams, uint256[], uint256[], LudusTypes.EventAttestationData) external returns (uint256);
    function startEvent(uint256) external;
    function completeEventAndDistribute(uint256, address[]) external;
    function cancelEvent(uint256) external;
    function enableETHYieldGeneration(uint256) external;
    function registerParticipant(uint256,uint256) external payable;
    function withdrawEventETH(uint256) external;
    function withdrawEventUSDC(uint256) external;
    function activateYieldGeneration(uint256) external;
    function setLudusWallet(address) external;
    function setSchemaIds(bytes32, bytes32) external;
    function setYieldManager(address) external;
    function approveAchievementTerminal() external;


    // --- Summaries of External Function Signatures Called by LudusEvents --- 
    // These define the interface LudusEvents expects from other contracts.

    // On YieldManager (IYieldManager)
    function yieldManager.setDistribution(uint256, uint256, uint256, uint256, address) external;
    function yieldManager.stakeEventFundsETH(uint256) external payable;
    function yieldManager.stakeEventFundsUSDC(uint256, uint256) external;
    function yieldManager.withdrawEventFundsETH(uint256) external returns (uint256);
    function yieldManager.withdrawEventFundsUSDC(uint256) external returns (uint256);
    function yieldManager.enableYieldGeneration(uint256) external;
    function yieldManager.usdc() external view returns (address);

    // On USDC (IERC20)
    function USDC.transfer(address, uint256) external returns (bool);
    function USDC.transferFrom(address, address, uint256) external returns (bool);
    function USDC.approve(address, uint256) external returns (bool);

    // On LudusIdentity (ILudusIdentity)
    function ludusIdentity.ownerOf(uint256) external view returns (address);
    function ludusIdentity.totalSupply() external view returns (uint256);

    // On EAS (IEAS)
    // For complex structs in CVL 2, it's often better to use a named type if possible,
    // or simplify to `bytes` if the internal structure isn't relevant to the rule.
    // Assuming AttestationRequestData can be represented as a tuple for now.
    // The IEAS.Attestation struct is (bytes32 schema, AttestationRequestData data)
    // AttestationRequestData is (address recipient, uint64 expirationTime, bool revocable, bytes32 refUID, bytes data, uint256 value)
    type AttestationRequestDataTuple = (address,uint64,bool,bytes32,bytes,uint256);
    type AttestationTuple = (bytes32, AttestationRequestDataTuple);
    function eas.attest(AttestationTuple) external payable returns (bytes32);
    
    // getAttestation returns a complex struct: Attestation
    // Attestation is (bytes32 uid, bytes32 schema, uint64 time, uint64 expirationTime, uint64 revocationTime, bytes32 refUID, address recipient, address attester, bool revocable, bytes data)
    type FullAttestationTuple = (bytes32,bytes32,uint64,uint64,uint64,bytes32,address,address,bool,bytes);
    function eas.getAttestation(bytes32) external view returns (FullAttestationTuple);

    // On SchemaRegistry (ISchemaRegistry)
    // Assuming schemaRegistry is primarily for the msg.sender check in completeEventAndDistribute and not other direct calls from LudusEvents relevant to this invariant.
    // If LudusEvents calls other ISchemaRegistry methods that affect state relevant to this invariant, they should be added.
}

/**
 * Invariant: Checks valid treasury distribution for all (relevant) eventIds.
 * This invariant ensures that for any event, the sum of percentage shares for athletes, 
 * organizer, and charity equals 9700 (97%), and if a charity share is defined, 
 * a valid charity address is also provided. This is based on the data stored in `eventDistributions`.
 */
invariant validTreasuryDistribution(uint256 eventId)
    checkTreasuryDistributionProperty(eventId); 